version: "3"
services:
  flask-sample:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /flask-sample
    volumes:
      - .:/flask-sample
    image: flask-sample-image
    container_name: flask-sample-container
    tty: true
    env_file: .env
